FROM node:10.15.3-alpine

RUN apk add --no-cache --virtual build-dependencies python make g++

RUN mkdir -p /home/node/${APP_DIR_NAME} && chown -R node:node /home/node/${APP_DIR_NAME}

WORKDIR /home/node/${APP_DIR_NAME}

COPY package*.json ./

RUN npm install node-gyp

RUN npm install --only=prod && apk del build-dependencies

RUN npm i typescript

USER node

COPY --chown=node:node . .

EXPOSE ${PORT}

CMD npm run start:prod
